# Generated by Django 2.2 on 2021-08-21 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesPlayed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_at_start', models.PositiveIntegerField()),
                ('credits_at_end', models.PositiveIntegerField()),
                ('credits_played', models.PositiveIntegerField()),
                ('credits_won', models.PositiveIntegerField()),
                ('_reelstop_blob', models.PositiveIntegerField(db_column='reelstops', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('played_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_games_played', to='site_app.User')),
            ],
        ),
    ]
