# Generated by Django 2.2 on 2021-09-05 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_user_games_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jackpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jackpots', to='site_app.User')),
                ('liked_by', models.ManyToManyField(related_name='jackpot_kudos', to='site_app.User')),
            ],
        ),
    ]
