game_reels = [
	['Lemon', 'Blank', 'Lemon', 'Blank', 'Strawberry', 'Blank', 'Banana', 'Blank', 'Cherry', 'Blank', 'Orange', 'Blank', 'Lemon', 'Blank', 'Banana', 'Blank', '2x', 'Blank', 'Orange', 'Blank', 'Lemon', 'Blank', 'Banana', 'Blank', 'Apple', 'Blank', 'Apple', 'Blank', 'Banana', 'Blank', 'Cherry', 'Blank', 'Apple', 'Blank', 'Lemon', 'Blank', 'Cherry', 'Blank', 'Strawberry', 'Blank', 'Strawberry', 'Blank', 'Strawberry', 'Blank', 'Orange', 'Blank', 'Lemon', 'Blank', '2x', 'Blank', 'Lemon', 'Blank', 'Cherry', 'Blank', 'Orange', 'Blank', '2x', 'Blank', 'Cherry', 'Blank', '2x', 'Blank', 'Strawberry', 'Blank', 'Apple', 'Blank', 'Banana', 'Blank', 'Banana', 'Blank', 'Lemon', 'Blank', 'Strawberry', 'Blank', 'Apple', 'Blank', 'Lemon', 'Blank', 'Cherry', 'Blank', 'Apple', 'Blank', '2x', 'Blank', 'Orange', 'Blank', 'Strawberry', 'Blank', 'Cherry', 'Blank', 'Orange', 'Blank', 'Strawberry', 'Blank', '2x', 'Blank', 'Apple', 'Blank', 'Banana', 'Blank', '2x', 'Blank', 'Banana', 'Blank', 'Orange', 'Blank', 'Strawberry', 'Blank', 'Strawberry', 'Blank', 'Strawberry', 'Blank', 'Lemon', 'Blank', 'Cherry', 'Blank', 'Strawberry', 'Blank', 'Apple', 'Blank', 'Banana', 'Blank', '2x', 'Blank', 'Orange', 'Blank', 'Orange', 'Blank', 'Strawberry', 'Blank', 'Banana', 'Blank', 'Orange', 'Blank', '2x', 'Blank', '2x', 'Blank', 'Cherry', 'Blank', 'Lemon', 'Blank', 'Banana', 'Blank', 'Banana', 'Blank', 'Cherry', 'Blank', '2x', 'Blank', 'Cherry', 'Blank', 'Lemon', 'Blank', 'Cherry', 'Blank', 'Cherry', 'Blank', 'Strawberry', 'Blank', 'Cherry', 'Blank', 'Orange', 'Blank', 'Cherry', 'Blank', '2x', 'Blank', 'Orange', 'Blank', 'Lemon', 'Blank', 'Lemon', 'Blank', 'Apple', 'Blank', 'Apple', 'Blank', 'Apple', 'Blank', '2x', 'Blank', 'Cherry', 'Blank', 'Lemon', 'Blank', 'Cherry', 'Blank', '2x', 'Blank', '2x', 'Blank', 'Cherry', 'Blank', 'Banana', 'Blank', 'Strawberry', 'Blank', 'Orange', 'Blank', 'Apple', 'Blank', 'Cherry', 'Blank', 'Orange', 'Blank', 'Orange', 'Blank', 'Lemon', 'Blank', 'Banana', 'Blank', 'Orange', 'Blank', 'Banana', 'Blank', '2x', 'Blank', 'Apple', 'Blank', 'Cherry', 'Blank', 'Orange', 'Blank', 'Orange', 'Blank', 'Strawberry', 'Blank', 'Apple', 'Blank', 'Apple', 'Blank', 'Apple', 'Blank', 'Cherry', 'Blank', 'Lemon', 'Blank', 'Apple', 'Blank', 'Strawberry', 'Blank', 'Apple', 'Blank', 'Apple', 'Blank', 'Strawberry', 'Blank', 'Lemon', 'Blank', 'Orange', 'Blank', 'Orange', 'Blank', 'Banana', 'Blank'],
	['Orange', 'Blank', 'Cherry', 'Blank', 'Lemon', 'Blank', 'Orange', 'Blank', 'Cherry', 'Blank', 'Strawberry', 'Blank', 'Lemon', 'Blank', 'Orange', 'Blank', '2x', 'Blank', '2x', 'Blank', 'Lemon', 'Blank', 'Lemon', 'Blank', '2x', 'Blank', 'Banana', 'Blank', 'Strawberry', 'Blank', 'Apple', 'Blank', 'Strawberry', 'Blank', '2x', 'Blank', '2x', 'Blank', 'Apple', 'Blank', 'Lemon', 'Blank', 'Banana', 'Blank', 'Cherry', 'Blank', 'Apple', 'Blank', 'Strawberry', 'Blank', 'Cherry', 'Blank', 'Banana', 'Blank', 'Banana', 'Blank', 'Banana', 'Blank', 'Cherry', 'Blank', 'Lemon', 'Blank', 'Lemon', 'Blank', 'Cherry', 'Blank', 'Lemon', 'Blank', 'Strawberry', 'Blank', 'Apple', 'Blank', 'Banana', 'Blank', 'Lemon', 'Blank', 'Cherry', 'Blank', 'Orange', 'Blank', 'Lemon', 'Blank', 'Lemon', 'Blank', 'Apple', 'Blank', 'Orange', 'Blank', 'Orange', 'Blank', 'Cherry', 'Blank', 'Orange', 'Blank', '2x', 'Blank', 'Cherry', 'Blank', 'Orange', 'Blank', 'Cherry', 'Blank', '2x', 'Blank', 'Strawberry', 'Blank', '2x', 'Blank', 'Lemon', 'Blank', 'Banana', 'Blank', 'Orange', 'Blank', 'Banana', 'Blank', 'Orange', 'Blank', 'Banana', 'Blank', 'Banana', 'Blank', 'Apple', 'Blank', 'Apple', 'Blank', 'Apple', 'Blank', '2x', 'Blank', '2x', 'Blank', 'Strawberry', 'Blank', '2x', 'Blank', 'Banana', 'Blank', 'Cherry', 'Blank', 'Banana', 'Blank', 'Banana', 'Blank', '2x', 'Blank', 'Cherry', 'Blank', 'Apple', 'Blank', 'Strawberry', 'Blank', '2x', 'Blank', 'Orange', 'Blank', '2x', 'Blank', 'Orange', 'Blank', 'Cherry', 'Blank', 'Lemon', 'Blank', 'Lemon', 'Blank', 'Apple', 'Blank', 'Orange', 'Blank', 'Cherry', 'Blank', 'Strawberry', 'Blank', 'Banana', 'Blank', 'Strawberry', 'Blank', 'Strawberry', 'Blank', 'Cherry', 'Blank', 'Orange', 'Blank', 'Orange', 'Blank', 'Strawberry', 'Blank', 'Strawberry', 'Blank', 'Orange', 'Blank', 'Cherry', 'Blank', 'Cherry', 'Blank', 'Orange', 'Blank', 'Orange', 'Blank', 'Apple', 'Blank', '2x', 'Blank', 'Apple', 'Blank', '2x', 'Blank', 'Cherry', 'Blank', 'Banana', 'Blank', 'Lemon', 'Blank', 'Lemon', 'Blank', 'Banana', 'Blank', '2x', 'Blank', 'Orange', 'Blank', 'Orange', 'Blank', 'Cherry', 'Blank', 'Cherry', 'Blank', 'Apple', 'Blank', 'Lemon', 'Blank', 'Apple', 'Blank', 'Lemon', 'Blank', 'Apple', 'Blank', 'Apple', 'Blank', 'Lemon', 'Blank', 'Cherry', 'Blank', 'Banana', 'Blank', 'Orange', 'Blank', 'Strawberry', 'Blank', '2x', 'Blank', 'Strawberry', 'Blank', 'Banana', 'Blank'],
	['2x', 'Blank', 'Lemon', 'Blank', 'Cherry', 'Blank', 'Strawberry', 'Blank', 'Cherry', 'Blank', '2x', 'Blank', 'Cherry', 'Blank', 'Lemon', 'Blank', '2x', 'Blank', 'Apple', 'Blank', '2x', 'Blank', 'Strawberry', 'Blank', 'Cherry', 'Blank', 'Apple', 'Blank', 'Apple', 'Blank', 'Cherry', 'Blank', '2x', 'Blank', 'Cherry', 'Blank', 'Cherry', 'Blank', 'Apple', 'Blank', 'Cherry', 'Blank', 'Orange', 'Blank', 'Orange', 'Blank', 'Apple', 'Blank', 'Cherry', 'Blank', 'Banana', 'Blank', 'Strawberry', 'Blank', 'Strawberry', 'Blank', 'Lemon', 'Blank', 'Lemon', 'Blank', 'Lemon', 'Blank', 'Orange', 'Blank', 'Strawberry', 'Blank', 'Apple', 'Blank', 'Orange', 'Blank', 'Strawberry', 'Blank', 'Orange', 'Blank', 'Strawberry', 'Blank', 'Cherry', 'Blank', 'Strawberry', 'Blank', 'Banana', 'Blank', 'Cherry', 'Blank', 'Strawberry', 'Blank', 'Lemon', 'Blank', 'Banana', 'Blank', 'Lemon', 'Blank', 'Lemon', 'Blank', 'Orange', 'Blank', '2x', 'Blank', 'Lemon', 'Blank', 'Banana', 'Blank', 'Lemon', 'Blank', 'Banana', 'Blank', 'Cherry', 'Blank', '2x', 'Blank', 'Banana', 'Blank', 'Apple', 'Blank', 'Strawberry', 'Blank', 'Orange', 'Blank', 'Cherry', 'Blank', 'Apple', 'Blank', 'Orange', 'Blank', 'Orange', 'Blank', 'Banana', 'Blank', 'Apple', 'Blank', 'Cherry', 'Blank', 'Apple', 'Blank', 'Orange', 'Blank', 'Lemon', 'Blank', 'Lemon', 'Blank', 'Orange', 'Blank', 'Apple', 'Blank', 'Orange', 'Blank', 'Banana', 'Blank', 'Apple', 'Blank', 'Banana', 'Blank', 'Strawberry', 'Blank', 'Banana', 'Blank', 'Apple', 'Blank', 'Lemon', 'Blank', 'Banana', 'Blank', 'Apple', 'Blank', 'Banana', 'Blank', 'Banana', 'Blank', 'Cherry', 'Blank', 'Lemon', 'Blank', 'Strawberry', 'Blank', 'Orange', 'Blank', 'Orange', 'Blank', 'Banana', 'Blank', '2x', 'Blank', 'Cherry', 'Blank', 'Lemon', 'Blank', '2x', 'Blank', 'Cherry', 'Blank', 'Orange', 'Blank', '2x', 'Blank', 'Banana', 'Blank', 'Strawberry', 'Blank', 'Banana', 'Blank', 'Strawberry', 'Blank', 'Cherry', 'Blank', '2x', 'Blank', 'Orange', 'Blank', 'Strawberry', 'Blank', 'Strawberry', 'Blank', 'Strawberry', 'Blank', 'Cherry', 'Blank', 'Strawberry', 'Blank', 'Orange', 'Blank', 'Banana', 'Blank', 'Orange', 'Blank', 'Apple', 'Blank', 'Apple', 'Blank', '2x', 'Blank', 'Orange', 'Blank', 'Lemon', 'Blank', 'Cherry', 'Blank', '2x', 'Blank', 'Apple', 'Blank', 'Cherry', 'Blank', '2x', 'Blank', 'Lemon', 'Blank', 'Apple', 'Blank', '2x', 'Blank', 'Strawberry', 'Blank', 'Lemon', 'Blank', 'Apple', 'Blank'],
]

wild = '2x'
wild_mult = 2

lines = [
    [1, 1, 1],
    [0, 0, 0],
    [2, 2, 2],
    [0, 1, 2],
    [2, 1, 0],
]

line_pays = {
	'2x' : [0, 1, 2, 500],
	'Cherry' : [0, 0, 0, 40],
	'Orange' : [0, 0, 0, 25],
	'Lemon' : [0, 0, 0, 15],
	'Apple' : [0, 0, 0, 10],
	'Banana' : [0, 0, 0, 5],
	'Strawberry' : [0, 0, 0, 2],
    'Blank' : [0, 0, 0, 0],
}

top_award = 500;

if __name__ == "__main__":
    pass
    # Add something later.